version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting build process..."
  build:
    commands:
      - echo "Copying DAG files to S3..."
      - aws s3 cp --recursive ./dags s3://airflow-managed-proj/dags/
      - echo "Copying requirements.txt files to S3..."
      - aws s3 cp ./requirements.txt s3://airflow-managed-proj/
      - echo "Copying Glue scripts to S3..."
      - aws s3 cp --recursive ./scripts s3://redshift-temp-17/scripts/ 

  post_build:
    commands:
      - echo "Build and deployment process complete!!!"