version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting build process..."
      - mkdir -p ./scripts    # Ensure the ./scripts directory exists
      - mkdir -p ./dags       # Ensure the ./dags directory exists
      - touch ./requirements.txt  # Ensure the requirements.txt file exists
  build:
    commands:
      - echo "Copying DAG files to S3..."
      - aws s3 cp --recursive ./dags s3://airflow-managed-proj/dags/
      - echo "Copying requirements.txt files to S3..."
      - aws s3 cp ./requirements.txt s3://airflow-managed-proj/
      - echo "Copying Glue scripts to S3..."
      - aws s3 cp --recursive ./scripts s3://aws-glue-assets-637423317099-ap-southeast-1/scripts/
  post_build:
    commands:
      - echo "Build and deployment process complete!!!"
